"""
Post-crew scaffolding: sets up the uv-managed Python backend, installs the
React frontend with npm, writes .gitignore, and makes the first git commit.
"""
import subprocess
from pathlib import Path

from rich.console import Console

console = Console()

_GITIGNORE = """\
# Python
.venv/
__pycache__/
*.pyc
*.pyo
.pytest_cache/
.ruff_cache/
dist/
build/
*.egg-info/

# Node / frontend
frontend/node_modules/
frontend/dist/
frontend/.vite/

# Env & OS
.env
.DS_Store
"""


def _run(cmd: list[str], cwd: Path, label: str, required: bool = True) -> bool:
    console.print(f"  [dim]$ {' '.join(cmd)}[/dim]")
    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        level = "[red]Error" if required else "[yellow]Warning"
        console.print(f"  {level} ({label}):[/] {result.stderr.strip() or result.stdout.strip()}")
        return False
    console.print(f"  [green]✓[/green] {label}")
    return True


def _read_txt(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [ln.strip() for ln in path.read_text(encoding="utf-8").splitlines()
            if ln.strip() and not ln.startswith("#")]


# ── Python backend (uv) ───────────────────────────────────────────────────────

def _scaffold_backend(project_dir: Path, project_name: str) -> None:
    console.print("\n[bold cyan]Backend — uv[/bold cyan]")

    _run(["uv", "init", "--name", project_name, "--no-readme"], cwd=project_dir, label="uv init")

    # Remove the stub uv creates if the Developer already wrote main files
    for stub in ["hello.py", "main.py"]:
        candidate = project_dir / stub
        if candidate.exists() and candidate.stat().st_size < 100:
            candidate.unlink()

    deps = _read_txt(project_dir / "deps.txt")
    if deps:
        _run(["uv", "add"] + deps, cwd=project_dir, label=f"uv add ({len(deps)} packages)")
    else:
        console.print("  [yellow]deps.txt not found — skipping uv add[/yellow]")

    _run(["uv", "add", "--dev", "pytest", "pytest-asyncio"], cwd=project_dir, label="uv add --dev pytest")
    _run(["uv", "sync"], cwd=project_dir, label="uv sync")


# ── React frontend (npm) ──────────────────────────────────────────────────────

def _scaffold_frontend(project_dir: Path) -> None:
    frontend_dir = project_dir / "frontend"
    if not frontend_dir.exists() or not (frontend_dir / "package.json").exists():
        console.print("\n  [dim]No frontend/package.json found — skipping npm install[/dim]")
        return

    console.print("\n[bold cyan]Frontend — npm[/bold cyan]")

    # Prefer npm; fall back gracefully if not available
    ok = _run(["npm", "install"], cwd=frontend_dir, label="npm install", required=False)
    if not ok:
        console.print(
            "  [yellow]npm install failed or npm not found.[/yellow]\n"
            f"  Run manually:  cd {frontend_dir} && npm install"
        )
        return

    # Type-check the generated frontend
    _run(["npm", "run", "build", "--", "--noEmit"], cwd=frontend_dir,
         label="tsc type-check", required=False)


# ── Git ───────────────────────────────────────────────────────────────────────

def _init_git(project_dir: Path, project_name: str) -> None:
    console.print("\n[bold cyan]Git[/bold cyan]")

    (project_dir / ".gitignore").write_text(_GITIGNORE, encoding="utf-8")
    console.print("  [green]✓[/green] .gitignore written")

    _run(["git", "init"], cwd=project_dir, label="git init")
    _run(["git", "add", "-A"], cwd=project_dir, label="git add -A")
    _run(
        ["git", "commit", "-m", "Initial commit — generated by openwally"],
        cwd=project_dir,
        label="git commit",
    )

    console.print(f"\n[bold green]Project ready:[/bold green] {project_dir}")
    console.print(
        f"\n  Push to GitHub (choose one):\n\n"
        f"    [cyan]gh repo create {project_name} --private --source={project_dir} --push[/cyan]\n\n"
        f"  or:\n\n"
        f"    git -C {project_dir} remote add origin git@github.com:<you>/{project_name}.git\n"
        f"    git -C {project_dir} push -u origin main\n"
    )


# ── Entry point ───────────────────────────────────────────────────────────────

def scaffold(project_dir: Path, project_name: str) -> None:
    console.print(f"\n[bold]Scaffolding:[/bold] {project_dir}")
    _scaffold_backend(project_dir, project_name)
    _scaffold_frontend(project_dir)
    _init_git(project_dir, project_name)
